# Maaz Ahmed
# Numpy

# Import NumPy as its abbreviation 'np'

In [1]:
import numpy as np

# Create a 1-dimensional NumPy array using np.array()


# Create a 2-dimensional NumPy array using np.array()


# Create a 3-dimensional Numpy array using np.array()

In [3]:
#  1D array
a = np.array([1,2,3])
print('1D Array\n',a)

# 2D array
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print('\n2D Array\n',b)

# 3D array
c = np.array([[[1,2,3],
               [4,5,6]],
                [[7,8,9],
                 [10,11,12]]])
print('\n3D Array\n',c)

1D Array
 [1 2 3]

2D Array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Now we've you've created 3 different arrays, let's find details about them.

# Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# 1D Array 
print('1D Array\nShape ---> ',a.shape)
print('\nNumber of dimensions ---> ',a.ndim)
print('\nData type ---> ',a.dtype)
print('\nSize ---> ',a.size)
print('\nType ---> ',type(a))

# 2D Array 
print('\n\n2D Array\nShape ---> ',b.shape)
print('\nNumber of dimensions ---> ',b.ndim)
print('\nData type ---> ',b.dtype)
print('\nSize ---> ',b.size)
print('\nType ---> ',type(b))

# 3D Array 
print('\n\n3D Array\nShape ---> ',c.shape)
print('\nNumber of dimensions ---> ',c.ndim)
print('\nData type ---> ',c.dtype)
print('\nSize ---> ',c.size)
print('\nType ---> ',type(c))


1D Array
Shape --->  (3,)

Number of dimensions --->  1

Data type --->  int32

Size --->  3

Type --->  <class 'numpy.ndarray'>


2D Array
Shape --->  (3, 3)

Number of dimensions --->  2

Data type --->  int32

Size --->  9

Type --->  <class 'numpy.ndarray'>


3D Array
Shape --->  (2, 2, 3)

Number of dimensions --->  3

Data type --->  int32

Size --->  12

Type --->  <class 'numpy.ndarray'>


# Import pandas

In [5]:
import pandas as pd

# Create a DataFrame out of one of the arrays you've created

In [7]:
#Converting Numpy 2D array to Pandas dataframe
df = pd.DataFrame(b)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


# Create an array of shape (10, 2) with only ones

In [20]:
one_array = np.ones(shape=(10,2))
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# Create an array of shape (7, 2, 3) of only zeros

In [23]:
zero_array = np.zeros(shape=(7,2,3))
zero_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

# Create an array within a range of 0 and 100 with step 3

In [27]:
# arrage(start_value,end_value,steps)
zerro_hun = np.arange(0,100,3)
zerro_hun

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

# Create a random array with numbers between 0 and 10 of size (7, 2)

In [41]:
np.random.randint(0,10,size=(7,2))

array([[5, 9],
       [3, 5],
       [1, 9],
       [1, 9],
       [3, 7],
       [6, 8],
       [7, 4]])


# Create a random array of floats between 0 & 1 of shape (3, 5)


In [40]:
np.random.random(size=(3,5))

array([[0.01326496, 0.94220176, 0.56328822, 0.3854165 , 0.01596625],
       [0.23089383, 0.24102547, 0.68326352, 0.60999666, 0.83319491],
       [0.17336465, 0.39106061, 0.18223609, 0.75536141, 0.42515587]])

# Set the random seed to 42


# Create a random array of numbers between 0 & 10 of size (4, 6)

In [43]:
np.random.seed(42)
np.random.randint(0,10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable


# Find the unique numbers in the array you just created

In [47]:
rand_array = np.random.randint(1,10,size=(3,7))
print(rand_array)
# uniqye() provide onlu unique no in the array
np.unique(rand_array)

[[2 5 8 9 9 1 9]
 [7 9 8 1 8 8 3]
 [1 8 3 3 1 5 7]]


array([1, 2, 3, 5, 7, 8, 9])


# Find the 0'th index of the latest array you created

In [50]:
rand_array[0]

array([2, 5, 8, 9, 9, 1, 9])

# Get the first 2 rows of latest array you created


In [53]:
rand_array[0:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

# Get the first 2 values of the first 2 rows of the latest array

In [60]:
rand_array[0:2, 0:2]

array([[2, 5],
       [7, 9]])

# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

In [66]:
rand_array = np.random.randint(0,10,size=(3,5))
print(rand_array)
one_array = np.ones(shape=(3,5))
print(one_array)

[[2 0 4 0 7]
 [0 0 1 1 5]
 [6 4 0 0 2]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Add the two arrays together


In [91]:
ans_array = rand_array + one_array
ans_array

array([[3., 1., 5., 1., 8.],
       [1., 1., 2., 2., 6.],
       [7., 5., 1., 1., 3.]])

# Create another array of ones of shape (5, 3)

In [70]:
another_array = np.ones(shape=(5,3))
another_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Try add the array of ones and the other most recent array together


In [75]:
ans_array = ans_array+another_array

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [78]:
# have swaped rows with colmns now can add these array
ans_array = ans_array+another_array.transpose()
ans_array

array([[ 7.,  5.,  9.,  5., 12.],
       [ 5.,  5.,  6.,  6., 10.],
       [11.,  9.,  5.,  5.,  7.]])

# Subtract the new array of ones from the other most recent array

In [82]:
ans_array = ans_array - one_array
ans_array

array([[3., 1., 5., 1., 8.],
       [1., 1., 2., 2., 6.],
       [7., 5., 1., 1., 3.]])

# Multiply the ones array with the latest array

In [86]:
ans_array = ans_array * one_array
ans_array

array([[ 6.,  2., 10.,  2., 16.],
       [ 2.,  2.,  4.,  4., 12.],
       [14., 10.,  2.,  2.,  6.]])

# Take the latest array to the power of 2 using '**'


In [90]:
ans_array = ans_array ** 2
ans_array

array([[ 9.,  1., 25.,  1., 64.],
       [ 1.,  1.,  4.,  4., 36.],
       [49., 25.,  1.,  1.,  9.]])

# Do the same thing with np.square()

In [95]:
np.square(ans_array)

array([[ 9.,  1., 25.,  1., 64.],
       [ 1.,  1.,  4.,  4., 36.],
       [49., 25.,  1.,  1.,  9.]])

# Find the mean of the latest array using np.mean()

In [96]:
ans_array.mean()

3.1333333333333333

In [97]:
# Find the maximum of the latest array using np.max()
np.max(ans_array)

8.0


# Find the minimum of the latest array using np.min()

In [98]:
np.min(ans_array)

1.0

# Find the standard deviation of the latest array

In [100]:
np.std(ans_array)

2.3626726862225804

# Find the variance of the latest array`

In [103]:
np.var(ans_array)

5.5822222222222235

# Reshape the latest array to (3, 5, 1)

In [104]:
print(ans_array)
ans_array.transpose()

[[3. 1. 5. 1. 8.]
 [1. 1. 2. 2. 6.]
 [7. 5. 1. 1. 3.]]


array([[3., 1., 7.],
       [1., 1., 5.],
       [5., 2., 1.],
       [1., 2., 1.],
       [8., 6., 3.]])

# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [2]:
array_one = np.random.randint(0,10,size=(3,3))
array_two = np.random.randint(0,10,size=(3,2))
print(array_one,'\n\n',array_two)

[[6 2 5]
 [4 0 6]
 [7 0 7]] 

 [[7 9]
 [4 1]
 [6 4]]


# Perform a dot product on the two newest arrays you created

In [3]:
np.dot(array_one,array_two)

array([[80, 76],
       [64, 60],
       [91, 91]])

# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

In [5]:
# first one have same rows as other column
np.dot(array_one,array_two.transpose())

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [17]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_one = np.random.randint(1,10,size=(6,5))
print(array_one)
array_two = np.random.randint(1,10,size=(6,5))
print(array_two)

[[2 5 4 4 4]
 [3 7 7 4 7]
 [6 6 7 4 9]
 [7 6 2 8 3]
 [6 9 7 5 1]
 [1 6 1 1 7]]
[[2 9 5 8 6]
 [3 7 9 6 2]
 [4 5 7 1 8]
 [2 2 9 5 5]
 [2 2 1 8 8]
 [8 4 9 9 4]]


# Compare the two arrays with '>'

In [18]:
array_one > array_two

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [ True,  True, False,  True,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True, False, False],
       [False,  True, False, False,  True]])


# Compare the two arrays with '>='

In [20]:
array_one >= array_two

array([[ True, False, False, False, False],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True, False, False],
       [False,  True, False, False,  True]])


# Find which elements of the first array are greater than 7

In [24]:
print(array_one[0,0] > 7)
print(array_two[0,0] > 7)

False
False


# Which parts of each array are equal? (try using '==')

In [25]:
array_one == array_two

array([[ True, False, False, False, False],
       [ True,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])


# Sort one of the arrays you just created in ascending order

In [35]:
np.sort(array_one)
array_one

array([[2, 5, 4, 4, 4],
       [3, 7, 7, 4, 7],
       [6, 6, 7, 4, 9],
       [7, 6, 2, 8, 3],
       [6, 9, 7, 5, 1],
       [1, 6, 1, 1, 7]])


# Sort the indexes of one of the arrays you just created

In [32]:
np.argsort(array_one)

array([[0, 2, 3, 4, 1],
       [0, 3, 1, 2, 4],
       [3, 0, 1, 2, 4],
       [2, 4, 1, 0, 3],
       [4, 3, 0, 2, 1],
       [0, 2, 3, 1, 4]], dtype=int64)


# Find the index with the maximum value in one of the arrays you've created

In [39]:
np.argmax(array_one)

14

# Find the index with the minimum value in one of the arrays you've created

In [48]:
new_array = np.random.randint(10,20,size=(3,4))
print(new_array)
np.argmin(new_array)

[[17 15 10 17]
 [12 12 10 10]
 [11 12 15 15]]


2

# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

In [47]:
np.argmax(array_one,axis=1)


array([1, 1, 4, 3, 1, 4], dtype=int64)

# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

In [51]:
print(np.argmin(new_array,axis=0))


[2 1 0 1]


# Create an array of normally distributed random numbers

In [52]:
np.random.randn(3, 5)

array([[ 2.05124526,  0.48133773,  0.93356722,  0.26394414,  1.66011414],
       [-0.79445839, -1.60957086,  0.65360726, -1.81093295, -0.56291894],
       [-1.17411385,  0.10922248,  0.25609984,  0.10827822, -0.33555116]])

# Create an array with 10 evenly spaced numbers between 1 and 100

In [53]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])